### ISSUE TITLE
Troubles with CherryPy...

### ISSUE THREAD

**Issue by jlegrand62** [rllynch/filament_watch#1]
Hello,
I was trying to install the python part inside a virtualenv as you proposed but I ran into an error. I think it is related to an API change in CherryPy, so I would like to know if you remember the version that you used to program you filament_watch script?

Thanks a lot for your work here!
Jonathan

In case I'm wrong about the source of the error, here is the full log:
```bash
(filament_watch_env) jonathan@jonathan-305U1A:~/Softwares/filament_watch$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to filament_watch.egg-info/requires.txt
writing filament_watch.egg-info/PKG-INFO
writing top-level names to filament_watch.egg-info/top_level.txt
writing dependency_links to filament_watch.egg-info/dependency_links.txt
writing entry points to filament_watch.egg-info/entry_points.txt
reading manifest file 'filament_watch.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'filament_watch.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/filament_watch
copying build/lib.linux-x86_64-2.7/filament_watch/octoprint_ctl.py -> build/bdist.linux-x86_64/egg/filament_watch
copying build/lib.linux-x86_64-2.7/filament_watch/filament_watch.py -> build/bdist.linux-x86_64/egg/filament_watch
copying build/lib.linux-x86_64-2.7/filament_watch/microcontroller_if.py -> build/bdist.linux-x86_64/egg/filament_watch
creating build/bdist.linux-x86_64/egg/filament_watch/static_www
copying build/lib.linux-x86_64-2.7/filament_watch/static_www/index.html -> build/bdist.linux-x86_64/egg/filament_watch/static_www
creating build/bdist.linux-x86_64/egg/filament_watch/static_www/css
copying build/lib.linux-x86_64-2.7/filament_watch/static_www/css/style.css -> build/bdist.linux-x86_64/egg/filament_watch/static_www/css
creating build/bdist.linux-x86_64/egg/filament_watch/static_www/js
copying build/lib.linux-x86_64-2.7/filament_watch/static_www/js/chart.js -> build/bdist.linux-x86_64/egg/filament_watch/static_www/js
copying build/lib.linux-x86_64-2.7/filament_watch/__init__.py -> build/bdist.linux-x86_64/egg/filament_watch
copying build/lib.linux-x86_64-2.7/filament_watch/web_server.py -> build/bdist.linux-x86_64/egg/filament_watch
byte-compiling build/bdist.linux-x86_64/egg/filament_watch/octoprint_ctl.py to octoprint_ctl.pyc
byte-compiling build/bdist.linux-x86_64/egg/filament_watch/filament_watch.py to filament_watch.pyc
byte-compiling build/bdist.linux-x86_64/egg/filament_watch/microcontroller_if.py to microcontroller_if.pyc
byte-compiling build/bdist.linux-x86_64/egg/filament_watch/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/filament_watch/web_server.py to web_server.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying filament_watch.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying filament_watch.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying filament_watch.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying filament_watch.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying filament_watch.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying filament_watch.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
filament_watch.web_server: module references __file__
creating 'dist/filament_watch-1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing filament_watch-1.0-py2.7.egg
removing '/home/jonathan/Softwares/filament_watch_env/lib/python2.7/site-packages/filament_watch-1.0-py2.7.egg' (and everything under it)
creating /home/jonathan/Softwares/filament_watch_env/lib/python2.7/site-packages/filament_watch-1.0-py2.7.egg
Extracting filament_watch-1.0-py2.7.egg to /home/jonathan/Softwares/filament_watch_env/lib/python2.7/site-packages
filament-watch 1.0 is already the active version in easy-install.pth
Installing filament_watch script to /home/jonathan/Softwares/filament_watch_env/bin

Installed /home/jonathan/Softwares/filament_watch_env/lib/python2.7/site-packages/filament_watch-1.0-py2.7.egg
Processing dependencies for filament-watch==1.0
Searching for cherrypy>=3.1
Reading https://pypi.python.org/simple/cherrypy/
Downloading https://pypi.python.org/packages/da/e2/6ed242ebfe96912e0866cc01139027d342d52c35ad33ee182bfb671c177d/CherryPy-10.1.1.tar.gz#md5=4957d9f40c7a0772ad4f2e3fbb5a627f
Best match: CherryPy 10.1.1
Processing CherryPy-10.1.1.tar.gz
Writing /tmp/easy_install-50grdE/CherryPy-10.1.1/setup.cfg
Running CherryPy-10.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-50grdE/CherryPy-10.1.1/egg-dist-tmp-0COlPU
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    'pyyaml'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 702, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 747, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    run_setup(setup_script, args)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-50grdE/CherryPy-10.1.1/setup.py", line 126, in <module>
    
  File "/tmp/easy_install-50grdE/CherryPy-10.1.1/setup.py", line 122, in main
    
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/dist.py", line 387, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/jonathan/Softwares/filament_watch_env/local/lib/python2.7/site-packages/setuptools/dist.py", line 166, in check_specifier
    except packaging.specifiers.InvalidSpecifier as error:
AttributeError: 'module' object has no attribute 'specifiers'
```

**Comment by jlegrand62** [comment]
installing cherrypy by pip (inside virtualenv) solved the problem!
